import "./globals.css";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/component/Navbar";
import PrelineScript from "@/component/PreLineScript";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="hs-overlay-body-open hs-overlay-body-open:overflow-hidden">
        <Navbar />
        {children}
      </body>
      <PrelineScript />
    </html>
  );
}
